"""create business tables

Revision ID: 7d34560e8aba
Revises: bc0a832224a4
Create Date: 2026-09-15 01:28:42.982521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7d34560e8aba'
down_revision: Union[str, Sequence[str], None] = 'bc0a832224a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classrooms',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('building', sa.String(length=50), nullable=False, comment='楼栋'),
    sa.Column('capacity', sa.SmallInteger(), nullable=False),
    sa.Column('room_type', sa.String(length=20), server_default='NORMAL', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='ACTIVE', nullable=False),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.CheckConstraint("room_type IN ('NORMAL','LAB','MULTIMEDIA')", name='ck_classrooms_type'),
    sa.CheckConstraint("status IN ('ACTIVE','MAINTENANCE','DISABLED')", name='ck_classrooms_status'),
    sa.CheckConstraint('capacity > 0', name='ck_classrooms_capacity'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    comment='教室',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_classrooms_building', 'classrooms', ['building'], unique=False)
    op.create_table('colleges',
    sa.Column('code', sa.String(length=20), nullable=False, comment='学院代码'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='学院名称'),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='ACTIVE', nullable=False),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.CheckConstraint("status IN ('ACTIVE','INACTIVE')", name='ck_colleges_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    comment='学院',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('evaluation_tasks',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('semester', sa.String(length=16), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='PENDING', nullable=False),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.CheckConstraint("status IN ('PENDING','ACTIVE','CLOSED')", name='ck_eval_task_status'),
    sa.CheckConstraint('end_time > start_time', name='ck_eval_task_time'),
    sa.PrimaryKeyConstraint('id'),
    comment='教学评价任务',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_eval_tasks_sem', 'evaluation_tasks', ['semester', 'status'], unique=False)
    op.create_table('selection_periods',
    sa.Column('semester', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('target_grade_year', sa.SmallInteger(), nullable=True, comment='限定年级，NULL 为全部'),
    sa.Column('status', sa.String(length=20), server_default='PENDING', nullable=False),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.CheckConstraint("status IN ('PENDING','ACTIVE','CLOSED')", name='ck_sel_period_status'),
    sa.CheckConstraint('end_time > start_time', name='ck_sel_period_time'),
    sa.PrimaryKeyConstraint('id'),
    comment='选课时间窗口',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_selection_period', 'selection_periods', ['semester', 'status'], unique=False)
    op.create_table('announcements',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('target_type', sa.String(length=20), server_default='ALL', nullable=False),
    sa.Column('publisher_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('is_top', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='DRAFT', nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.CheckConstraint("status IN ('DRAFT','PUBLISHED','WITHDRAWN')", name='ck_ann_status'),
    sa.CheckConstraint("target_type IN ('ALL','STUDENT','TEACHER')", name='ck_ann_target'),
    sa.ForeignKeyConstraint(['publisher_id'], ['users.id'], name='fk_ann_publisher', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='通知公告',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_announcements_pub', 'announcements', ['status', 'target_type', 'published_at'], unique=False)
    op.create_table('courses',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('college_id', mysql.BIGINT(unsigned=True), nullable=False, comment='开课学院'),
    sa.Column('course_type', sa.String(length=20), nullable=False),
    sa.Column('credits', sa.Numeric(precision=4, scale=1), nullable=False, comment='学分'),
    sa.Column('total_hours', sa.SmallInteger(), nullable=False, comment='总学时'),
    sa.Column('theory_hours', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('practice_hours', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('exam_type', sa.String(length=20), server_default='EXAM', nullable=False, comment='EXAM 考试 / CHECK 考查'),
    sa.Column('regular_weight', sa.Numeric(precision=3, scale=2), server_default='0.40', nullable=False, comment='平时成绩权重'),
    sa.Column('final_weight', sa.Numeric(precision=3, scale=2), server_default='0.60', nullable=False, comment='期末成绩权重'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='ACTIVE', nullable=False),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.CheckConstraint("course_type IN ('REQUIRED','ELECTIVE','PUBLIC_REQUIRED','PUBLIC_ELECTIVE','PRACTICE')", name='ck_courses_type'),
    sa.CheckConstraint("exam_type IN ('EXAM','CHECK')", name='ck_courses_exam_type'),
    sa.CheckConstraint("status IN ('ACTIVE','INACTIVE')", name='ck_courses_status'),
    sa.CheckConstraint('credits > 0', name='ck_courses_credits'),
    sa.CheckConstraint('regular_weight + final_weight = 1.00', name='ck_courses_weight'),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], name='fk_courses_college', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    comment='课程',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_courses_college_type', 'courses', ['college_id', 'course_type'], unique=False)
    op.create_table('majors',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('college_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('degree_type', sa.String(length=20), server_default='BACHELOR', nullable=False),
    sa.Column('duration_years', mysql.TINYINT(unsigned=True), server_default='4', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='ACTIVE', nullable=False),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.CheckConstraint("degree_type IN ('BACHELOR','MASTER','DOCTOR')", name='ck_majors_degree'),
    sa.CheckConstraint("status IN ('ACTIVE','INACTIVE')", name='ck_majors_status'),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], name='fk_majors_college', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    comment='专业',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_majors_college', 'majors', ['college_id'], unique=False)
    op.create_table('operation_logs',
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=True, comment='登录失败时可能为空'),
    sa.Column('username', sa.String(length=50), nullable=True, comment='冗余快照，用户删除后仍可追溯'),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('module', sa.String(length=40), nullable=False),
    sa.Column('resource_type', sa.String(length=40), nullable=True),
    sa.Column('resource_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('detail', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='兼容 IPv6'),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('result', sa.String(length=20), server_default='SUCCESS', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='主键'),
    sa.CheckConstraint("result IN ('SUCCESS','FAILURE')", name='ck_oplogs_result'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_oplogs_user', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='操作日志',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_oplogs_action_time', 'operation_logs', ['action', 'created_at'], unique=False)
    op.create_index('idx_oplogs_resource', 'operation_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index('idx_oplogs_user_time', 'operation_logs', ['user_id', 'created_at'], unique=False)
    op.create_table('teachers',
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('teacher_no', sa.String(length=30), nullable=False, comment='工号'),
    sa.Column('college_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('title', sa.String(length=20), nullable=True, comment='职称'),
    sa.Column('gender', sa.String(length=10), server_default='UNKNOWN', nullable=False),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='ACTIVE', nullable=False),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.CheckConstraint("status IN ('ACTIVE','LEAVE','RETIRED')", name='ck_teachers_status'),
    sa.CheckConstraint("title IS NULL OR title IN ('ASSISTANT','LECTURER','ASSOCIATE_PROFESSOR','PROFESSOR')", name='ck_teachers_title'),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], name='fk_teachers_college', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_teachers_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_no'),
    sa.UniqueConstraint('user_id'),
    comment='教师档案',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_teachers_college', 'teachers', ['college_id'], unique=False)
    op.create_table('classes',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('major_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('grade_year', sa.SmallInteger(), nullable=False, comment='入学年份'),
    sa.Column('counselor_id', mysql.BIGINT(unsigned=True), nullable=True, comment='辅导员'),
    sa.Column('student_count', sa.SmallInteger(), server_default='0', nullable=False, comment='冗余计数，学籍变更时同步'),
    sa.Column('status', sa.String(length=20), server_default='ACTIVE', nullable=False),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.CheckConstraint("status IN ('ACTIVE','INACTIVE')", name='ck_classes_status'),
    sa.ForeignKeyConstraint(['counselor_id'], ['teachers.id'], name='fk_classes_counselor', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['major_id'], ['majors.id'], name='fk_classes_major', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    comment='行政班级',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_classes_major_grade', 'classes', ['major_id', 'grade_year'], unique=False)
    op.create_table('course_prerequisites',
    sa.Column('course_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('prerequisite_course_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('min_score', sa.Numeric(precision=5, scale=2), server_default='60.00', nullable=False, comment='先修课最低成绩要求'),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.CheckConstraint('course_id <> prerequisite_course_id', name='ck_course_prereq_self'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name='fk_prereq_course', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prerequisite_course_id'], ['courses.id'], name='fk_prereq_prereq', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'prerequisite_course_id', name='uk_course_prereq'),
    comment='先修课程关系',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('curriculum_plans',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('major_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('grade_year', sa.SmallInteger(), nullable=False, comment='适用年级'),
    sa.Column('total_credits_required', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('required_credits', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('elective_credits', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='DRAFT', nullable=False),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.CheckConstraint("status IN ('DRAFT','PUBLISHED','ARCHIVED')", name='ck_curriculum_status'),
    sa.ForeignKeyConstraint(['major_id'], ['majors.id'], name='fk_curriculum_major', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('major_id', 'grade_year', name='uk_curriculum_major_year'),
    comment='培养方案',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('teaching_tasks',
    sa.Column('semester', sa.String(length=16), nullable=False, comment='学期，如 2026-2027-1'),
    sa.Column('course_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('college_id', mysql.BIGINT(unsigned=True), nullable=False, comment='承担学院'),
    sa.Column('planned_classes', sa.SmallInteger(), server_default='1', nullable=False, comment='计划开班数'),
    sa.Column('status', sa.String(length=20), server_default='DRAFT', nullable=False),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.CheckConstraint("status IN ('DRAFT','CONFIRMED','CANCELLED')", name='ck_teaching_tasks_status'),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], name='fk_tt_college', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name='fk_tt_course', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('semester', 'course_id', 'college_id', name='uk_teaching_tasks'),
    comment='教学任务',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_teaching_tasks_semester', 'teaching_tasks', ['semester'], unique=False)
    op.create_table('curriculum_courses',
    sa.Column('plan_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('course_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('suggested_semester', mysql.TINYINT(unsigned=True), nullable=False, comment='建议修读学期 1~8'),
    sa.Column('is_required', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name='fk_cc_course', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['plan_id'], ['curriculum_plans.id'], name='fk_cc_plan', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'course_id', name='uk_curriculum_courses'),
    comment='培养方案课程',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_curriculum_courses_sem', 'curriculum_courses', ['plan_id', 'suggested_semester'], unique=False)
    op.create_table('students',
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('student_no', sa.String(length=30), nullable=False, comment='学号'),
    sa.Column('class_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('major_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('college_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('gender', sa.String(length=10), server_default='UNKNOWN', nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('enrollment_year', sa.SmallInteger(), nullable=False),
    sa.Column('academic_status', sa.String(length=20), server_default='ENROLLED', nullable=False),
    sa.Column('total_credits', sa.Numeric(precision=5, scale=1), server_default='0.0', nullable=False, comment='已修总学分'),
    sa.Column('gpa', sa.Numeric(precision=3, scale=2), nullable=True, comment='平均绩点'),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.CheckConstraint("academic_status IN ('ENROLLED','SUSPENDED','GRADUATED','WITHDRAWN')", name='ck_students_status'),
    sa.CheckConstraint("gender IN ('MALE','FEMALE','UNKNOWN')", name='ck_students_gender'),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name='fk_students_class', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], name='fk_students_college', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['major_id'], ['majors.id'], name='fk_students_major', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_students_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_no'),
    sa.UniqueConstraint('user_id'),
    comment='学生档案',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_students_class', 'students', ['class_id'], unique=False)
    op.create_index('idx_students_college_year', 'students', ['college_id', 'enrollment_year'], unique=False)
    op.create_index('idx_students_major', 'students', ['major_id'], unique=False)
    op.create_table('teaching_classes',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('task_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('course_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('semester', sa.String(length=16), nullable=False),
    sa.Column('teacher_id', mysql.BIGINT(unsigned=True), nullable=True, comment='授课教师，排课前可为空'),
    sa.Column('capacity', sa.SmallInteger(), nullable=False, comment='容量上限'),
    sa.Column('selected_count', sa.SmallInteger(), server_default='0', nullable=False, comment='已选人数；必须在事务内与选课记录同步'),
    sa.Column('selection_status', sa.String(length=20), server_default='CLOSED', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='ACTIVE', nullable=False),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.CheckConstraint("selection_status IN ('CLOSED','OPEN','FINISHED')", name='ck_tc_sel'),
    sa.CheckConstraint("status IN ('ACTIVE','CANCELLED')", name='ck_tc_status'),
    sa.CheckConstraint('capacity > 0', name='ck_tc_capacity'),
    sa.CheckConstraint('selected_count >= 0', name='ck_tc_count'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name='fk_tc_course', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_id'], ['teaching_tasks.id'], name='fk_tc_task', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], name='fk_tc_teacher', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    comment='教学班',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_tc_selection', 'teaching_classes', ['selection_status', 'semester'], unique=False)
    op.create_index('idx_tc_semester_course', 'teaching_classes', ['semester', 'course_id'], unique=False)
    op.create_index('idx_tc_teacher', 'teaching_classes', ['teacher_id'], unique=False)
    op.create_table('course_selections',
    sa.Column('student_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('teaching_class_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('course_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('semester', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='SELECTED', nullable=False),
    sa.Column('selected_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('dropped_at', sa.DateTime(), nullable=True),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.CheckConstraint("status IN ('SELECTED','DROPPED')", name='ck_selection_status'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name='fk_sel_course', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='fk_sel_student', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teaching_class_id'], ['teaching_classes.id'], name='fk_sel_tc', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'teaching_class_id', name='uk_selection'),
    comment='选课记录',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_selection_student_sem', 'course_selections', ['student_id', 'semester'], unique=False)
    op.create_index('idx_selection_tc', 'course_selections', ['teaching_class_id', 'status'], unique=False)
    op.create_table('evaluations',
    sa.Column('task_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('student_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('teaching_class_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('teacher_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.CheckConstraint('score BETWEEN 0 AND 100', name='ck_evaluations_score'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='fk_eval_student', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['evaluation_tasks.id'], name='fk_eval_task', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], name='fk_eval_teacher', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['teaching_class_id'], ['teaching_classes.id'], name='fk_eval_tc', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'student_id', 'teaching_class_id', name='uk_evaluations'),
    comment='教学评价',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_evaluations_tc', 'evaluations', ['teaching_class_id'], unique=False)
    op.create_index('idx_evaluations_teacher', 'evaluations', ['teacher_id'], unique=False)
    op.create_table('exams',
    sa.Column('teaching_class_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('course_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('semester', sa.String(length=16), nullable=False),
    sa.Column('exam_type', sa.String(length=20), server_default='FINAL', nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('duration_minutes', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='DRAFT', nullable=False),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.CheckConstraint("exam_type IN ('FINAL','MAKEUP','RETAKE')", name='ck_exams_type'),
    sa.CheckConstraint("status IN ('DRAFT','PUBLISHED','FINISHED')", name='ck_exams_status'),
    sa.CheckConstraint('end_time > start_time', name='ck_exams_time'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name='fk_exams_course', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['teaching_class_id'], ['teaching_classes.id'], name='fk_exams_tc', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='考试',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_exams_date', 'exams', ['exam_date', 'start_time'], unique=False)
    op.create_index('idx_exams_tc', 'exams', ['teaching_class_id'], unique=False)
    op.create_table('grades',
    sa.Column('student_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('teaching_class_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('course_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('semester', sa.String(length=16), nullable=False),
    sa.Column('regular_score', sa.Numeric(precision=5, scale=2), nullable=True, comment='平时成绩'),
    sa.Column('final_score', sa.Numeric(precision=5, scale=2), nullable=True, comment='期末成绩'),
    sa.Column('total_score', sa.Numeric(precision=5, scale=2), nullable=True, comment='总评，由后端按课程权重计算'),
    sa.Column('grade_point', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('credits', sa.Numeric(precision=4, scale=1), nullable=False, comment='学分快照'),
    sa.Column('is_passed', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='DRAFT', nullable=False),
    sa.Column('submitted_by', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('reject_reason', sa.String(length=500), nullable=True),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.CheckConstraint("status IN ('DRAFT','SUBMITTED','APPROVED','REJECTED')", name='ck_grades_status'),
    sa.CheckConstraint('final_score IS NULL OR final_score BETWEEN 0 AND 100', name='ck_grades_final'),
    sa.CheckConstraint('regular_score IS NULL OR regular_score BETWEEN 0 AND 100', name='ck_grades_regular'),
    sa.CheckConstraint('total_score IS NULL OR total_score BETWEEN 0 AND 100', name='ck_grades_total'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name='fk_grades_approver', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name='fk_grades_course', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='fk_grades_student', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitted_by'], ['teachers.id'], name='fk_grades_submitter', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['teaching_class_id'], ['teaching_classes.id'], name='fk_grades_tc', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'teaching_class_id', name='uk_grades'),
    comment='成绩',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_grades_student_sem', 'grades', ['student_id', 'semester'], unique=False)
    op.create_index('idx_grades_tc_status', 'grades', ['teaching_class_id', 'status'], unique=False)
    op.create_table('schedules',
    sa.Column('teaching_class_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('classroom_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('day_of_week', mysql.TINYINT(unsigned=True), nullable=False, comment='1=周一 … 7=周日'),
    sa.Column('start_period', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('end_period', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('start_week', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('end_week', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('week_type', sa.String(length=10), server_default='ALL', nullable=False, comment='ALL / ODD / EVEN'),
    sa.Column('semester', sa.String(length=16), nullable=False),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.CheckConstraint("week_type IN ('ALL','ODD','EVEN')", name='ck_schedules_wtype'),
    sa.CheckConstraint('day_of_week BETWEEN 1 AND 7', name='ck_schedules_day'),
    sa.CheckConstraint('start_period >= 1 AND end_period >= start_period', name='ck_schedules_period'),
    sa.CheckConstraint('start_week >= 1 AND end_week >= start_week', name='ck_schedules_week'),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], name='fk_sched_room', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['teaching_class_id'], ['teaching_classes.id'], name='fk_sched_tc', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='排课',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_schedules_conflict', 'schedules', ['semester', 'day_of_week', 'classroom_id'], unique=False)
    op.create_index('idx_schedules_tc', 'schedules', ['teaching_class_id'], unique=False)
    op.create_index('idx_schedules_time', 'schedules', ['semester', 'day_of_week', 'start_period', 'end_period'], unique=False)
    op.create_table('exam_rooms',
    sa.Column('exam_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('classroom_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('capacity', sa.SmallInteger(), nullable=False),
    sa.Column('assigned_count', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('invigilator_id', mysql.BIGINT(unsigned=True), nullable=True, comment='监考教师'),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.CheckConstraint('capacity > 0', name='ck_exam_rooms_capacity'),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], name='fk_er_room', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], name='fk_er_exam', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invigilator_id'], ['teachers.id'], name='fk_er_invigilator', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id', 'classroom_id', name='uk_exam_rooms'),
    comment='考场',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('exam_students',
    sa.Column('exam_room_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('student_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('seat_no', sa.SmallInteger(), nullable=True),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['exam_room_id'], ['exam_rooms.id'], name='fk_es_room', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='fk_es_student', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_room_id', 'student_id', name='uk_exam_students'),
    comment='考场学生分配',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_exam_students_student', 'exam_students', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_exam_students_student', table_name='exam_students')
    op.drop_table('exam_students')
    op.drop_table('exam_rooms')
    op.drop_index('idx_schedules_time', table_name='schedules')
    op.drop_index('idx_schedules_tc', table_name='schedules')
    op.drop_index('idx_schedules_conflict', table_name='schedules')
    op.drop_table('schedules')
    op.drop_index('idx_grades_tc_status', table_name='grades')
    op.drop_index('idx_grades_student_sem', table_name='grades')
    op.drop_table('grades')
    op.drop_index('idx_exams_tc', table_name='exams')
    op.drop_index('idx_exams_date', table_name='exams')
    op.drop_table('exams')
    op.drop_index('idx_evaluations_teacher', table_name='evaluations')
    op.drop_index('idx_evaluations_tc', table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index('idx_selection_tc', table_name='course_selections')
    op.drop_index('idx_selection_student_sem', table_name='course_selections')
    op.drop_table('course_selections')
    op.drop_index('idx_tc_teacher', table_name='teaching_classes')
    op.drop_index('idx_tc_semester_course', table_name='teaching_classes')
    op.drop_index('idx_tc_selection', table_name='teaching_classes')
    op.drop_table('teaching_classes')
    op.drop_index('idx_students_major', table_name='students')
    op.drop_index('idx_students_college_year', table_name='students')
    op.drop_index('idx_students_class', table_name='students')
    op.drop_table('students')
    op.drop_index('idx_curriculum_courses_sem', table_name='curriculum_courses')
    op.drop_table('curriculum_courses')
    op.drop_index('idx_teaching_tasks_semester', table_name='teaching_tasks')
    op.drop_table('teaching_tasks')
    op.drop_table('curriculum_plans')
    op.drop_table('course_prerequisites')
    op.drop_index('idx_classes_major_grade', table_name='classes')
    op.drop_table('classes')
    op.drop_index('idx_teachers_college', table_name='teachers')
    op.drop_table('teachers')
    op.drop_index('idx_oplogs_user_time', table_name='operation_logs')
    op.drop_index('idx_oplogs_resource', table_name='operation_logs')
    op.drop_index('idx_oplogs_action_time', table_name='operation_logs')
    op.drop_table('operation_logs')
    op.drop_index('idx_majors_college', table_name='majors')
    op.drop_table('majors')
    op.drop_index('idx_courses_college_type', table_name='courses')
    op.drop_table('courses')
    op.drop_index('idx_announcements_pub', table_name='announcements')
    op.drop_table('announcements')
    op.drop_index('idx_selection_period', table_name='selection_periods')
    op.drop_table('selection_periods')
    op.drop_index('idx_eval_tasks_sem', table_name='evaluation_tasks')
    op.drop_table('evaluation_tasks')
    op.drop_table('colleges')
    op.drop_index('idx_classrooms_building', table_name='classrooms')
    op.drop_table('classrooms')
    # ### end Alembic commands ###
