"""create rbac tables

Revision ID: bc0a832224a4
Revises: 
Create Date: 2026-09-15 01:14:16.042116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bc0a832224a4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('code', sa.String(length=80), nullable=False, comment='权限码，格式 <资源>:<动作>'),
    sa.Column('name', sa.String(length=80), nullable=False, comment='权限名称'),
    sa.Column('module', sa.String(length=40), nullable=False, comment='所属模块'),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    comment='系统权限',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_permissions_module', 'permissions', ['module'], unique=False)
    op.create_table('roles',
    sa.Column('code', sa.String(length=30), nullable=False, comment='角色代码'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='角色名称'),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('is_builtin', sa.Boolean(), server_default='0', nullable=False, comment='内置角色不可删除'),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    comment='系统角色',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False, comment='登录名；学生为学号，教师为工号'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='密码哈希'),
    sa.Column('real_name', sa.String(length=50), nullable=False, comment='真实姓名'),
    sa.Column('user_type', sa.String(length=20), nullable=False, comment='STUDENT / TEACHER / ADMIN'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='邮箱'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='手机号'),
    sa.Column('status', sa.String(length=20), server_default='ACTIVE', nullable=False, comment='账号状态'),
    sa.Column('last_login_at', sa.DateTime(), nullable=True, comment='最后登录时间'),
    sa.Column('failed_login_count', sa.SmallInteger(), server_default='0', nullable=False, comment='连续登录失败次数'),
    sa.Column('locked_until', sa.DateTime(), nullable=True, comment='锁定到期时间'),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.CheckConstraint("status IN ('ACTIVE','DISABLED','LOCKED')", name='ck_users_status'),
    sa.CheckConstraint("user_type IN ('STUDENT','TEACHER','ADMIN')", name='ck_users_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    comment='统一用户账号',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_users_type_status', 'users', ['user_type', 'status'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('permission_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='主键'),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name='fk_role_perms_perm', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='fk_role_perms_role', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uk_role_permissions'),
    comment='角色-权限关联',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('user_roles',
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('role_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='主键'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='fk_user_roles_role', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_roles_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uk_user_roles'),
    comment='用户-角色关联',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    op.drop_table('role_permissions')
    op.drop_index('idx_users_type_status', table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_index('idx_permissions_module', table_name='permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###
